#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil expand-links:t f:t
#+options: inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t
#+title: Lógica Digital
#+date: 2024-11-24
#+author: José Armando Sarango Cuenca.
#+email: jose.sarango@epn.edu.ec
#+language: Español
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.7.5)
#+cite_export: biblatex

#+latex_class: article
#+latex_class_options:
#+latex_header:
#+latex_header_extra:
#+description:
#+keywords:
#+subtitle:
#+latex_footnote_command: \footnote{%s%s}
#+latex_engraved_theme:
#+latex_compiler: pdflatex

#+latex_header: \usepackage{fancyhdr}
#+latex_header: \usepackage[top=25mm, left=25mm, right=25mm]{geometry}
#+latex_header: \usepackage{longtable}
#+latex_header: \fancyhead[R]{}
#+latex_header: \setlength\headheight{43.0pt} 

#+begin_export latex
\fancyhead[C]{\includegraphics[scale=0.05]{.././LOGICA/logoEPN.jpg}\\
ESCUELA POLITÉCNICA NACIONAL\\FACULTAD DE INGENIERÍA DE SISTEMAS\\
ARQUITECTURA DE COMPUTADORES}
\thispagestyle{fancy}
#+end_export



* Objetivos de Aprendizaje
- Comprender las operaciones del álgebra de Boole
- Comprender la estructura de un computador
- Diseñar circuitos combinacionales simples
- Ejercitar reducción con mapa de K.
- Ejercitar uso de Emacs
* Instrucciones
1. Completar el desarrollo de los ejercicios propuestos
2. Subir al aula virtual su archivo .org y el .pdf generado

* Ejercicios
1. A partir de la tabla de verdad de la compuerta OR exclusiva de dos
   entradas obtenga la función booleana como SOP (min-términos).
   - Complete la siguiente tabla. Después de modificar la tabla
     ejecutar ~C-c C-c~ o dar un ~TAB~ para que la tabla se ajuste
     automáticamente
   - Escriba la expresión en SOP usando \LaTeX

     La Tabla de la XOR es:
     |---+---+--------------|
     | A | B | $A \oplus B$ |
     |---+---+--------------|
     | 0 | 0 |            0 |
     | 0 | 1 |            1 |
     | 1 | 0 |            1 |
     | 1 | 1 |            0 |
     |---+---+--------------|

     A partir de la Tabla, en SOP,\\
     $A=0,B=1$ y $A=1,B=0$
    -  El termino es $$A \oplus B = \overline{A}B + A\overline{B}$$


2. Para el ejercicio anterior obtenga la representación en POS
   (max-términos).
   - $$A=0,B=0$$ y $A=1,B=1$
   - $$A\oplus B = (A+B)*(\overline{A}+\overline{B})$$

3. ¿Puede representar el circuito sólo con compuertas NAND?
   - Utilice las leyes de Morgan para obtener una representación sólo
     con compuertas NAND. Recuerde que una compuerta NAND es una
     compuerta AND negada

     El siguiente código de \LaTeX permite alinear una ecuación con
     respecto de un símbolo. Realice las sustituciones de acuerdo al
     enunciado y obtenga la expresión en compuertas NAND.
     
     \begin{align*}
       F &= x^2 - y^2 \\
       F &= (x-y)(x+y)
     \end{align*}
   - Respuesta:
 
\begin{align*}
x - y &= \overline{xy} \\
      &= \overline{x}\overline{x} \\
x + y &= \overline{\overline{x \overline{y}}} \\
      &= \overline{x} \overline{y} \\
F &= (x - y)(x + y) \\
F &= \overline{\overline{x y} \overline{x \overline{y}}}
\end{align*}

4. Simplificar $F = ACD+\bar{A}BCD. Resp:$CD(A+B)

   De igual manera se puede usar el siguiente código \LaTeX para
   escribir el desarrollo matemático
   \begin{align*}
     F &= ACD+\bar{A}BCD \\
   \end{align*}

\begin{align*}
F &= ACD + \overline{A}BCD \\
F &= CD(AC + \overline{A}BC) \quad \text{(Factorización de $CD$)} \\
F &= CD((A + \overline{A})B + AC) \quad \text{(Distribución)} \\
F &= CD(A + B) \quad \text{(Propiedad del complemento: $A + \overline{A} = 1$)}
\end{align*}

   De acuerdo a la tabla de reglas del álgebra de Boole ¿qué reglas ha
   utilizado? Use M-RET (i.e. ALT-ENTER) para producir el siguiente
   item numerado una vez que ha terminado el anterior

   1. Regla de factorización

   2. Regla del complemento

   3. Regla de simplificación


5. Simplificar $F=ABC+A\bar{B} \overline{\bar{A}\bar{C}}$. R: $A(\bar{B}+C)$

   \begin{align*}
     F &=ABC+A\bar{B} \overline{\bar{A}\bar{C}} \\
   \end{align*}
\begin{align*}
F &= ABC + A\bar{B} \overline{\overline{A}\overline{C}} \\
F &= ABC + A\bar{B}(A + C) \quad \text{(Ley de doble negación)} \\
F &= ABC + A\bar{B}A + A\bar{B}C \quad \text{(Distribución)} \\
F &= ABC + A\bar{B} + A\bar{B}C \\
F &= ABC + A\bar{B}(1 + C) \quad \text{(Ley de la identidad: $1 + C = 1$)} \\
F &= ABC + A\bar{B} \\
F &= A(BC + \bar{B}) \\
F &= A(\bar{B} + C) \quad \text{(Distribución)}
\end{align*}

6. A partir de la Tabla [[tab-ejercicio]] de verdad obtener la
   representación en SOP.


#+CAPTION: Ejercicio de tres variables
#+NAME: tab-ejercicio
+--+--+--+--+
|A  B  C | F|
+--+--+--+--+
|0   0  0|0 |
|0   0  1|0 |
|0   1  0|1 |
|0   1  1|1 |
|1   0  0|0 |
|1   0  1|0 |
|1   1  0|1 |
|1   1  1|0 |
+--+--+--+--+

-Respuesta:
La representación en forma de suma de productos (SOP) de la tabla de verdad es: \\

F = \overline{A}B\overline{C} + \overline{A}BC + AB\overline{C}


7. Usando Mapas de Karnaugh obtenga la simplificación del circuito de
   la Tabla [[tab-ejercicio]]
   
La tabla aquí propuesta se edita con ~C-c '~. Una vez hechos los
cambios si se desea aceptar se vuelve a ejecutar ~C-c '~.

+---+----+----+----+----+
|   | BC | BC | BC | BC |
+---+----+----+----+----+
| A | 00 | 01 | 11 | 10 |
+---+----+----+----+----+
| 0 |    |    | 1  |  1 |
+---+----+----+----+----+
| 1 |    |    |    | 1  |
+---+----+----+----+----+



La simplificación del circuito es: \\
F = B(\overline{A} + \overline{C})



